name: Bump version and create a GitHub Release
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - modules/*/docs/**
      - modules/*/README.md
      - ./*
jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.generate_tag.outputs.new_tag }}
      changelog: ${{ steps.generate_tag.outputs.changelog }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Generate a new tag
        id: generate_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  create-release:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ needs.bump-version.outputs.new_tag }}
          name: ${{ needs.bump-version.outputs.new_tag }}
          body: ${{ needs.bump-version.outputs.changelog }}
