name: Semantic checks
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths-ignore:
      - .github/**
      - docs/**
      - "*"
jobs:
  verify-tag-config-collision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Check next tag to be generated
        id: next_collection_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Check there's no collisions on next tag
        run: |
          git fetch --all --tags >/dev/null 2>&1
          if [ $(git tag --list "${{ steps.next_collection_version.outputs.new_tag }}" ) ]; then
            echo "::error ::Next tag already exists in git"
            exit 1
          else
            echo "::notice ::Next tag is not present in git, proceeding."
            exit 0
          fi
  # TODO: Add a CHANGELOG requirement
  # TODO: Add a constraint to edit at most one module per PR
