name: Semantic checks
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - modules/**
jobs:
  tag-config-collision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Check next tag to be generated
        id: next_collection_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Check there's no collisions on next tag
        run: |
          git fetch --all --tags >/dev/null 2>&1
          if [ $(git tag --list "${{ steps.next_collection_version.outputs.new_tag }}" ) ]; then
            echo "::error ::Next tag already exists in git"
            exit 1
          else
            echo "::notice ::Next tag is not present in git, proceeding."
            exit 0
          fi
  one-module-per-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo, all branches, all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed directories
        id: changed_module_dirs
        uses: tj-actions/changed-files@v35.9.0
        with:
          json: true
          dir_names: true
          dir_names_exclude_root: true
          files_ignore: |
            modules/**/docs/*
      - name: Count changed directories
        id: changed_module_dirs_count
        uses: mikefarah/yq@v4.33.3
        with:
          cmd: yq 'length' <(echo "${{ steps.changed_module_dirs.outputs.all_changed_files }}")
      - name: Fail if changed module count is not 1
        if: ${{ steps.changed_module_dirs_count.outputs.result > 1 }}
        run: |
          echo "::error ::You are attempting to change more than one module. Please limit your PR to one module."
          exit 1
  # TODO: Add a CHANGELOG requirement
